In [ ]:
import numpy as np

In [ ]:
numbers = np.arange(1, 6)

In [ ]:
numbers

### Multiplying every element of the array by 2.

In [ ]:
numbers * 2

### Cubing every element of the array by 2.

In [ ]:
numbers ** 3

### Using Augmented Assignment Operator to add values to the elements of the array

In [ ]:
numbers += 10

In [ ]:
numbers

### Creating an array of floating point numbers with a gap of 5


In [ ]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [ ]:
numbers2

### Multiplying arrays

In [13]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

In [14]:
numbers

array([11, 12, 13, 14, 15])

### Comparing every elements of the array to a number

In [16]:
numbers >= 13

array([False, False,  True,  True,  True])

In [17]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [18]:
numbers == numbers2

array([False, False, False, False, False])

In [19]:
numbers == numbers

array([ True,  True,  True,  True,  True])

# Self Check
* Create an array of the values 1 through 5 then use broadcasting to square each value.

In [20]:
aray = np.arange(1, 6)
aray

array([1, 2, 3, 4, 5])

In [21]:
squared = aray ** 2
squared

array([ 1,  4,  9, 16, 25], dtype=int32)

### Paul's Answer

In [22]:
np.arange(1, 6) ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)