# <u> * NUMPY * </u>
#### <u> * Learning the basics of NUMPY * </u>

In [ ]:
import numpy as np

In [ ]:
numbers = np.array([2, 3, 5, 7, 11, 9876])

In [ ]:
type(numbers)

In [ ]:
numbers # Look at the formatting DUDE!!! It's cool...

In [ ]:
np.array([[1, 2, 3, 987654], [4, 5, 6, 8715263]])

# # <u> * Self Check * </u>
* Create a one-dimensional array from a list comprehension that produces the even integers from 2 through 20.
* Create a 2-by-5 array containing the even integers from 2 through 10 in the first row and the odd integers from 1 through 9 in the second row.

## <u> * My Answer * </u>

In [7]:
np.array([item for item in range(1, 21) if item % 2 == 0])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## <u> * Paul's Answer * </u>

In [11]:
import numpy as np

np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## <u> * My Answer * </u>

In [12]:
np.array([[item for item in range(1, 11) if item % 2 == 0], [i for i in range(0, 10) if i % 2 != 0]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

## <u> * Paul's Answer * </u>

In [13]:
np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])