# <u> * Creating Arrays With Specific Values. * </u>

In [60]:
import numpy as np

In [ ]:
np.zeros(5)

####  <u> * In the above example the values in the arrays are showing up as floats * </u>
### <u> * Defining a Data Type in the Array  * </u>

####  <u> * In the below example 2 is for number of arrays, and 4 is for number of elements in each array, dtype specifies the type of data. * </u> 

In [ ]:
np.ones((2, 4), dtype=int)

### <u> * Using FULL to define other values * </u>

In [ ]:
np.full((3, 5), 13)

In [ ]:
np.full((5, 7), 'Apple')

In [ ]:
import random

In [ ]:
np.full((3, 5), random.randint(1, 7))

## <u> * Creating an array with a Range of numbers * </u>

In [57]:
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

## <u> * Creating an array that decrements by 2 starting from 10  * </u>

In [58]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

## <u> * Creating a floating point range using LINSPACE * </u>

### <u> * In the below example the min value is 0.0 and the max value is 1.0 and the 5 denotes dividing the range in 5 equal parts * </u>

In [59]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## <u> * Creating a range of values and turning it into a multi dimensional array using RESHAPING * </u>
* In the below example we are taking the range of values between 1 and 21 and creating 4 arrays of 5 elements each.

In [61]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### <u> * This is how Numpy summarizes the data if it is too big * </u>

In [62]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [63]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

# <u> * Self Check * </u>
* Use NumPy function arange to create an array of 20 even integers from 2 through 40, then reshape the reshape the result into a 4 by 5 array.

In [66]:
np.arange(2, 41, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])