# <u> * Deep Copy * </u>
* Deep Copy creates a copy of data that has physically seperate copy of data in the memory.
* Modification to one of the array will not change the element on the other.

In [1]:
import numpy as np

In [2]:
number1 = np.arange(1, 11)

In [3]:
number1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
number2 = number1.copy()

In [5]:
number2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### <u> * Changing the element on one array to see if the change shows up on another one * </u>

In [6]:
number1[1] *= 10

In [7]:
number1

array([ 1, 20,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
number2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## <u> * If you want to make a copy of other types of data then use the Deep Copy function. * </u>