# <u> * Indexing And Slicing Numpy Arrays * </u>

In [ ]:
import numpy as np

In [ ]:
grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])

In [ ]:
grades

#### <u> * If we need to access number 96 from the first row and second column this is how we do it. * </u>

In [ ]:
grades[0, 1]

In [ ]:
grades[1] # Accessing only row 1

In [ ]:
grades[0:2] # Getting the first two rows of the array

In [ ]:
grades[0:3] # Getting the first three rows of the array

In [ ]:
grades[3:] # Getting all the arrays after row three

#### <u> * Picking up rows as per our choices * </u>

In [ ]:
grades[[1, 3]] # Getting only the row number 1 and 3

## <u> * Picking the columns now * </u>

In [ ]:
grades[:, 0] # Getting only column 0

In [ ]:
grades[:, 1] # Picking the column 1

In [ ]:
grades[:, 1:3] # Selecting all the columns starting from column 1 and 2 but not 3

In [ ]:
grades[:, [0, 2]] # Select only column 0 and 2

## <u> * Self Check * </u>
#### <u> * Given the following array, write statements to perform the following tasks * </u>
* Select the second row
* Select the first and third row
* Select the middle three columns


In [ ]:
import numpy as np

In [ ]:

data = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])

In [ ]:
data

In [ ]:
data[1]

In [ ]:
data[[0, 2]]

In [ ]:
data[:, 1:4]


## <u> * Paul's Answer * </u>
* Since it is a contiguous number from 1 through 15 he has used the range operation and reshape operation

In [27]:
import numpy as np

In [28]:
a = np.arange(1, 16).reshape(3, 5)

In [29]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
a[1]

array([ 6,  7,  8,  9, 10])

In [31]:
a[[0, 2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [32]:
data[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])