# <u> * Numpy Calculation Methods * </u>
####  * We are going to look into various inbuilt calculation methods in Numpy * 

In [ ]:
import numpy as np
grades = np.array([[87, 96, 70], [100, 87, 90], [94, 77, 90], [100, 81, 82]])
grades

In [ ]:
grades.sum() # Sum is going to add all the grades and give me a total

In [ ]:
grades.min() # Gets me the minimum value out of the all the grades

In [ ]:
grades.max()

In [ ]:
grades.mean() # Getting the average of all the grades when sumed up

In [ ]:
grades.std() # Getting the standard deviation

In [ ]:
grades.var() # Getting variance

#### <u> * In the above case we are performing the operation in the entire data set. That is the entire rows and columns. How about if we want to perform the operation on only specific data set inside the array? * </u>

In [ ]:
grades.mean(axis=0) # Axis = 0 here referes to all the COLUMNS

In [ ]:
grades.mean(axis=1) # Axis = 1 here referes to all the ROWS

In [ ]:
grades.mean? # This is how to refer the help section

## <u> * Self Check * </u>
* User numpy random-number generation to create an array of twelve random grades in the range 60 through 100, then reshape the result into 3-by-4 array. Calculate the averages of all the grades, the averages of the grades in each column and the averages of the grades in each row.

In [9]:
import numpy as np

In [10]:
grades = np.random.randint(60, 101, 20).reshape(4, 5)
grades

array([[79, 62, 94, 79, 65],
       [90, 80, 73, 94, 97],
       [78, 60, 85, 82, 67],
       [86, 61, 91, 92, 68]])

In [11]:
grades.mean()

79.15

In [12]:
grades.mean(axis = 0)

array([83.25, 65.75, 85.75, 86.75, 74.25])

In [13]:
grades.mean(axis = 1)

array([75.8, 86.8, 74.4, 79.6])