# <u> * Reshaping and Transposing Numpy Arrays * </u>
* Reshaping is creating a reshaped view method, hence it does not modify the original array shape in memory.

In [1]:
import numpy as np

In [2]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [3]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

#### <u> * Creating a one row six column from the above multidimensional array * </u>

In [4]:
grades.reshape(1, 6)

array([[ 87,  96,  70, 100,  87,  90]])

#### <u> * Since this is just a view, it does not modify the original array * </u>

In [5]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

## <u> * If you want to physically reshape the array then use the resize method * </u>

In [8]:
grades.resize(1, 6)

In [9]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

# <u> * Flatten and Ravel  * </u>
### <u> * This lets us take a multi dimensional array and flatten it into single dimension. The difference between Flatten and Ravel is that Flatten creates a DEEP COPY and Ravel creates a SHALLOW COPY * </u>

In [10]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [11]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [12]:
flattened = grades.flatten()

In [13]:
flattened

array([ 87,  96,  70, 100,  87,  90])

In [14]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

### <u> * Now making a change in the flattenend array will not change the data in the original array * </u>

In [15]:
flattened[0] = 100

In [16]:
flattened

array([100,  96,  70, 100,  87,  90])

In [17]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

### <u> * Using the RAVEL method to make a SHALLOW COPY * </u>
* This will also create a single dimensional, but it will be a shalllow copy, which means that changing the elements on either of the data will result in changing the element on the other set of data as well. 

In [18]:
ravelled = grades.ravel()

In [19]:
ravelled

array([ 87,  96,  70, 100,  87,  90])

In [20]:
ravelled[0] = 99

In [21]:
ravelled

array([ 99,  96,  70, 100,  87,  90])

In [22]:
grades

array([[ 99,  96,  70],
       [100,  87,  90]])

# <u> * Transposing * </u>
* Transposing change the rows to columns and columns to row.
* It creats a view and not a deep copy
* The numbers of rows and columns will change

In [23]:
grades.T

array([[ 99, 100],
       [ 96,  87],
       [ 70,  90]])

### <u> * Horizontal and Vertical Stacking of Data * </u>

In [24]:
marks = np.array([[94, 77, 90], [100, 81, 82]])

In [25]:
marks

array([[ 94,  77,  90],
       [100,  81,  82]])

In [26]:
grades

array([[ 99,  96,  70],
       [100,  87,  90]])

In [27]:
np.hstack((grades, marks))

array([[ 99,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [29]:
np.vstack((grades, marks))

array([[ 99,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

# <u> * Self Check * </u>

In [44]:
import numpy as np

In [45]:
a = np.arange(1, 7).reshape(2, 3)

In [46]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a = np.hstack((a, a))

In [48]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [49]:
a = np.vstack((a, a))

In [50]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])