# <u> * VIEWS: Shallow Copy * </u>

In [8]:
import numpy as np

In [9]:
numbers = np.arange(1, 6)

In [10]:
numbers

array([1, 2, 3, 4, 5])

In [11]:
numbers2 = numbers.view()

In [12]:
numbers2

array([1, 2, 3, 4, 5])

#### <u> * Though we have two arrays now numbers and numbers2. Lets check their IDs to see if they are referring to the same memory location. * </u>
#### <u> * It looks like they are physically located in seperate memory! * </u>

In [13]:
id(numbers)

100881976

In [14]:
id(numbers2)

100884376

#### <u> * Let's modify numbers to see if that results in change in number2. * </u>
#### <u> * And it looks like changing the elements in 1st array results in change in the 2nd array as well when 2nd array is create as a view of 1st array * </u>

In [15]:
numbers[1] *= 10

In [16]:
numbers

array([ 1, 20,  3,  4,  5])

In [17]:
numbers2

array([ 1, 20,  3,  4,  5])

#### <u> * Making a change in 2nd array again results is the change showing up in both the arrays. * </u>

In [18]:
numbers2[1] /= 10

In [19]:
numbers2

array([1, 2, 3, 4, 5])

In [20]:
numbers

array([1, 2, 3, 4, 5])

## <u> * Creating Views with Slices * </u>

In [21]:
numbers2 = numbers[0:3]

In [22]:
numbers2

array([1, 2, 3])